# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [14]:
!pip install numpy

import numpy as np


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\Mahad\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)
print(A)
print()

# Dimension (number of axes)
print("Dimension:", np.ndim(A))

# Shape
print("Shape:", np.shape(A))

# Size 
print("Size:", np.size(A))

# Datatype
print("Datatype:", A.dtype.name)




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Dimension: 2
Shape: (3, 5)
Size: 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)
print()

subtraction = B - C
print(subtraction)
print()

multiplication = B * C
print(multiplication)
print()

matrix_multiplication = B @ C
print(matrix_multiplication)




[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [5]:
B = np.arange(1, 10).reshape(3, 3)
print(B)
print()

# Exponentiate each element in the matrix
np.exp(B)
print(np.exp(B))
print()

# Minimum value in the whole matrix
min_value = np.min(B)
print(min_value)
print()

# Minimum value in each row
min_value_per_row = np.min(B, axis=1)
print(min_value_per_row)
print()

# Minimum value in each column
min_value_per_column = np.min(B, axis=0)
print(min_value_per_column)
print()

# Index of the minimum value in the whole matrix
min_index = np.argmin(B)
print(min_index)
print()

# Index of the minimum value in each row
min_index_per_row = np.argmin(B, axis=1)
print(min_index_per_row)
print()

# Sum of all elements in the matrix
sum_of_elements = np.sum(B)
print(sum_of_elements)
print()

# Mean for each column
mean_per_column = np.mean(B, axis=0)
print(mean_per_column)
print()

# Median for each column
median_per_column = np.median(B, axis=0)
print(median_per_column)



[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

1

[1 4 7]

[1 2 3]

0

[0 0 0]

45

[4. 5. 6.]

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [31]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [34]:
A[1]


array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:

Om du skriver färre index än antalet dimensioner i en numpy-array så visar numpy automatiskt allt för de delar du inte specificerat.
A[1] visar hela raden på plats 1, alltså [6, 7, 8, 9, 10]. Eftersom man bara skrev radnumret, så tar numpy med alla kolumner för den raden.





### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [35]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [7]:
A = np.array(A)

for element in np.nditer(A):
    print(element)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [8]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
Svar:
Koden skapar en 1D array a med siffrorna från 0 till 29. Sedan omformas a till en 3D array b med formen (2, 3, 5):

b har 3 axlar:
- Den första axeln har 2 lager.
- Den andra axeln har 3 rader i varje lager.
- Den tredje axeln har 5 kolumner i varje rad.

b är en 3D array med 2 lager, där varje lager har 3 rader och 5 kolumner.



### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [9]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [10]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [11]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [12]:
def add_mult_matrices(matrix1, matrix2, operation):
    # numpy arrays
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        print("Error")
        return
    
    # add' or 'multiply
    if operation not in ['add', 'multiply']:
        print("Error")
        return
    
    # adding matrices
    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            print("Error")
            return
        result = matrix1 + matrix2
        print("Svar addition:")
        print(result)
    
    # multiplying matrices
    elif operation == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            print("Error")
            return
        result = matrix1 @ matrix2
        print("Svar multiplication:")
        print(result)

# Example:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# addition:
add_mult_matrices(A, B, 'add')
print()
# multiplication:
add_mult_matrices(A, B, 'multiply')



Svar addition:
[[ 6  8]
 [10 12]]

Svar multiplication:
[[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [3]:
## Uppgift 10.1.1

# Definiera vektorn x
x = np.array([4, 3])
print("uppgift 10.1.1")
# a) Vilken dimension har vektorn x?
print(f"a) Dimensionen av x: {len(x)}")

# b) Beräkna 5x
five_x = 5 * x
print(f"b) 5x = {five_x}")

# c) Beräkna 3x
three_x = 3 * x
print(f"c) 3x = {three_x}")

# d) Beräkna 5x + 3x
sum_x = five_x + three_x
print(f"d) 5x + 3x = {sum_x}")

# e) Beräkna 8x
eight_x = 8 * x
print(f"e) 8x = {eight_x}")

# f) Beräkna 4x - x
four_x_minus_x = 4 * x - x
print(f"f) 4x - x = {four_x_minus_x}")

# g) Beräkna x^T (transponering av x)
x_transpose = x.T  # Transponera x
print(f"g) x^T = {x_transpose}")



# h) Är x + x^T definierat?
if x.shape == x_transpose.shape:
    result = x + x_transpose
    print(f"h) x + x^T = \n{result}")
else:
    print("h) x + x^T är inte definierat (olika dimensioner)")


# i) Beräkna ||x|| (normen av x)
norm_x = np.linalg.norm(x)
print(f"i) ||x|| = {norm_x}")
print()

## Uppgift 10.1.2
# Definiera vektorn v
v = np.array([3, 7, 0, 11])

# a) Vilken dimension har vektorn v?
print(f"a) Dimensionen av v: {len(v)}")

# b) Beräkna 2v
two_v = 2 * v
print(f"b) 2v = {two_v}")

# c) Beräkna 5v + 2v
result_c = 5 * v + 2 * v
print(f"c) 5v + 2v = {result_c}")

# d) Beräkna 4v - 2v
result_d = 4 * v - 2 * v
print(f"d) 4v - 2v = {result_d}")

# e) Transponering av v
v_transpose = v.reshape(-1, 1)  # Omvandla till en kolumnvektor
print(f"e) v^T = {v_transpose}")
print(f"Dimension efter transponering: {v_transpose.shape}")

# f) 
norm_v = np.linalg.norm(v)
print(f"f){norm_v}")
print()

# Uppgift 10.1.3
print("uppgift 10.1.3")
# Definiera vektorerna v1 och v2
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# a) Beräkna ||v1|| (normen av v1)
norm_v1 = np.linalg.norm(v1)
print(f"a){norm_v1}")

# b) Beräkna ||v1 - v2||
# Först subtrahera v1 och v2 elementvis, sedan beräkna normen av skillnaden
diff_v1_v2 = v1 - v2
norm_diff = np.linalg.norm(diff_v1_v2)
print(f"b){norm_diff}")



uppgift 10.1.1
a) Dimensionen av x: 2
b) 5x = [20 15]
c) 3x = [12  9]
d) 5x + 3x = [32 24]
e) 8x = [32 24]
f) 4x - x = [12  9]
g) x^T = [4 3]
h) x + x^T = 
[8 6]
i) ||x|| = 5.0

a) Dimensionen av v: 4
b) 2v = [ 6 14  0 22]
c) 5v + 2v = [21 49  0 77]
d) 4v - 2v = [ 6 14  0 22]
e) v^T = [[ 3]
 [ 7]
 [ 0]
 [11]]
Dimension efter transponering: (4, 1)
f)13.379088160259652

uppgift 10.1.3
a)7.14142842854285
b)4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [67]:
v1 = np.arange(4)
v2 = v1[-2:]
print('Before changing:', v1)
print('Before changing:', v2)

# Change the last element in v2
v2[-1] = 123

print("\nAfter changing the last element in v2:")
print("v1:", v1)
print("v2:", v2)


Before changing: [0 1 2 3]
Before changing: [2 3]

After changing the last element in v2:
v1: [  0   1   2 123]
v2: [  2 123]


In [45]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

v1 = np.arange(4)  # v1 is a numpy array [0, 1, 2, 3]
v2 = v1[-2:]       # v2 is a slice of the last two elements of v1

print(v1.base)  
print(v2.base)  


None
[0 1 2 3]


In [68]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
